DROP TABLE IF EXISTS public.account;
CREATE TABLE public.account
(acc_id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
iban CHAR(2) NOT NULL,
bic CHAR(3) NOT NULL);

INSERT INTO account (iban, bic) VALUES 
('i1','aaa'),
('i2','bbb'),
('i3','ccc');
